{
  BaseClient: [class BaseClient extends EventEmitter],
  Client: [class Client extends BaseClient],
  Shard: [class Shard extends EventEmitter],
  ShardClientUtil: [class ShardClientUtil],
  ShardingManager: [class ShardingManager extends EventEmitter],
  WebhookClient: [class WebhookClient extends BaseClient],
  ActivityFlags: [class ActivityFlags extends BitField] {
    FLAGS: {
      INSTANCE: 1,
      JOIN: 2,
      SPECTATE: 4,
      JOIN_REQUEST: 8,
      SYNC: 16,
      PLAY: 32
    }
  },
  ApplicationFlags: [class ApplicationFlags extends BitField] {
    FLAGS: {
      GATEWAY_PRESENCE: 4096,
      GATEWAY_PRESENCE_LIMITED: 8192,
      GATEWAY_GUILD_MEMBERS: 16384,
      GATEWAY_GUILD_MEMBERS_LIMITED: 32768,
      VERIFICATION_PENDING_GUILD_LIMIT: 65536,
      EMBEDDED: 131072
    }
  },
  BaseManager: [class BaseManager],
  BitField: [class BitField] { FLAGS: {}, defaultBit: 0 },
  Collection: <ref *1> [class Collection extends Map] {
    default: [Circular *1]
  },
  Constants: {
    Package: {
      name: 'discord.js',
      version: '13.3.1',
      description: 'A powerful library for interacting with the Discord API',
      scripts: [Object],
      main: './src/index.js',
      types: './typings/index.d.ts',
      files: [Array],
      directories: [Object],
      contributors: [Array],
      license: 'Apache-2.0',
      keywords: [Array],
      repository: [Object],
      bugs: [Object],
      homepage: 'https://discord.js.org',
      dependencies: [Object],
      devDependencies: [Object],
      engines: [Object]
    },
    UserAgent: 'DiscordBot (https://discord.js.org, 13.3.1) Node.js/v16.6.1',
    WSCodes: {
      '1000': 'WS_CLOSE_REQUESTED',
      '4004': 'TOKEN_INVALID',
      '4010': 'SHARDING_INVALID',
      '4011': 'SHARDING_REQUIRED',
      '4013': 'INVALID_INTENTS',
      '4014': 'DISALLOWED_INTENTS'
    },
    Endpoints: {
      CDN: [Function: CDN],
      invite: [Function: invite],
      botGateway: '/gateway/bot'
    },
    Status: {
      READY: 0,
      CONNECTING: 1,
      RECONNECTING: 2,
      IDLE: 3,
      NEARLY: 4,
      DISCONNECTED: 5,
      WAITING_FOR_GUILDS: 6,
      IDENTIFYING: 7,
      RESUMING: 8
    },
    Opcodes: {
      DISPATCH: 0,
      HEARTBEAT: 1,
      IDENTIFY: 2,
      STATUS_UPDATE: 3,
      VOICE_STATE_UPDATE: 4,
      VOICE_GUILD_PING: 5,
      RESUME: 6,
      RECONNECT: 7,
      REQUEST_GUILD_MEMBERS: 8,
      INVALID_SESSION: 9,
      HELLO: 10,
      HEARTBEAT_ACK: 11
    },
    Events: {
      RATE_LIMIT: 'rateLimit',
      INVALID_REQUEST_WARNING: 'invalidRequestWarning',
      API_RESPONSE: 'apiResponse',
      API_REQUEST: 'apiRequest',
      CLIENT_READY: 'ready',
      APPLICATION_COMMAND_CREATE: 'applicationCommandCreate',
      APPLICATION_COMMAND_DELETE: 'applicationCommandDelete',
      APPLICATION_COMMAND_UPDATE: 'applicationCommandUpdate',
      GUILD_CREATE: 'guildCreate',
      GUILD_DELETE: 'guildDelete',
      GUILD_UPDATE: 'guildUpdate',
      GUILD_UNAVAILABLE: 'guildUnavailable',
      GUILD_MEMBER_ADD: 'guildMemberAdd',
      GUILD_MEMBER_REMOVE: 'guildMemberRemove',
      GUILD_MEMBER_UPDATE: 'guildMemberUpdate',
      GUILD_MEMBER_AVAILABLE: 'guildMemberAvailable',
      GUILD_MEMBERS_CHUNK: 'guildMembersChunk',
      GUILD_INTEGRATIONS_UPDATE: 'guildIntegrationsUpdate',
      GUILD_ROLE_CREATE: 'roleCreate',
      GUILD_ROLE_DELETE: 'roleDelete',
      INVITE_CREATE: 'inviteCreate',
      INVITE_DELETE: 'inviteDelete',
      GUILD_ROLE_UPDATE: 'roleUpdate',
      GUILD_EMOJI_CREATE: 'emojiCreate',
      GUILD_EMOJI_DELETE: 'emojiDelete',
      GUILD_EMOJI_UPDATE: 'emojiUpdate',
      GUILD_BAN_ADD: 'guildBanAdd',
      GUILD_BAN_REMOVE: 'guildBanRemove',
      CHANNEL_CREATE: 'channelCreate',
      CHANNEL_DELETE: 'channelDelete',
      CHANNEL_UPDATE: 'channelUpdate',
      CHANNEL_PINS_UPDATE: 'channelPinsUpdate',
      MESSAGE_CREATE: 'messageCreate',
      MESSAGE_DELETE: 'messageDelete',
      MESSAGE_UPDATE: 'messageUpdate',
      MESSAGE_BULK_DELETE: 'messageDeleteBulk',
      MESSAGE_REACTION_ADD: 'messageReactionAdd',
      MESSAGE_REACTION_REMOVE: 'messageReactionRemove',
      MESSAGE_REACTION_REMOVE_ALL: 'messageReactionRemoveAll',
      MESSAGE_REACTION_REMOVE_EMOJI: 'messageReactionRemoveEmoji',
      THREAD_CREATE: 'threadCreate',
      THREAD_DELETE: 'threadDelete',
      THREAD_UPDATE: 'threadUpdate',
      THREAD_LIST_SYNC: 'threadListSync',
      THREAD_MEMBER_UPDATE: 'threadMemberUpdate',
      THREAD_MEMBERS_UPDATE: 'threadMembersUpdate',
      USER_UPDATE: 'userUpdate',
      PRESENCE_UPDATE: 'presenceUpdate',
      VOICE_SERVER_UPDATE: 'voiceServerUpdate',
      VOICE_STATE_UPDATE: 'voiceStateUpdate',
      TYPING_START: 'typingStart',
      WEBHOOKS_UPDATE: 'webhookUpdate',
      INTERACTION_CREATE: 'interactionCreate',
      ERROR: 'error',
      WARN: 'warn',
      DEBUG: 'debug',
      SHARD_DISCONNECT: 'shardDisconnect',
      SHARD_ERROR: 'shardError',
      SHARD_RECONNECTING: 'shardReconnecting',
      SHARD_READY: 'shardReady',
      SHARD_RESUME: 'shardResume',
      INVALIDATED: 'invalidated',
      RAW: 'raw',
      STAGE_INSTANCE_CREATE: 'stageInstanceCreate',
      STAGE_INSTANCE_UPDATE: 'stageInstanceUpdate',
      STAGE_INSTANCE_DELETE: 'stageInstanceDelete',
      GUILD_STICKER_CREATE: 'stickerCreate',
      GUILD_STICKER_DELETE: 'stickerDelete',
      GUILD_STICKER_UPDATE: 'stickerUpdate'
    },
    ShardEvents: {
      CLOSE: 'close',
      DESTROYED: 'destroyed',
      INVALID_SESSION: 'invalidSession',
      READY: 'ready',
      RESUMED: 'resumed',
      ALL_READY: 'allReady'
    },
    PartialTypes: [Object: null prototype] {
      USER: 'USER',
      CHANNEL: 'CHANNEL',
      GUILD_MEMBER: 'GUILD_MEMBER',
      MESSAGE: 'MESSAGE',
      REACTION: 'REACTION'
    },
    WSEvents: [Object: null prototype] {
      READY: 'READY',
      RESUMED: 'RESUMED',
      APPLICATION_COMMAND_CREATE: 'APPLICATION_COMMAND_CREATE',
      APPLICATION_COMMAND_DELETE: 'APPLICATION_COMMAND_DELETE',
      APPLICATION_COMMAND_UPDATE: 'APPLICATION_COMMAND_UPDATE',
      GUILD_CREATE: 'GUILD_CREATE',
      GUILD_DELETE: 'GUILD_DELETE',
      GUILD_UPDATE: 'GUILD_UPDATE',
      INVITE_CREATE: 'INVITE_CREATE',
      INVITE_DELETE: 'INVITE_DELETE',
      GUILD_MEMBER_ADD: 'GUILD_MEMBER_ADD',
      GUILD_MEMBER_REMOVE: 'GUILD_MEMBER_REMOVE',
      GUILD_MEMBER_UPDATE: 'GUILD_MEMBER_UPDATE',
      GUILD_MEMBERS_CHUNK: 'GUILD_MEMBERS_CHUNK',
      GUILD_INTEGRATIONS_UPDATE: 'GUILD_INTEGRATIONS_UPDATE',
      GUILD_ROLE_CREATE: 'GUILD_ROLE_CREATE',
      GUILD_ROLE_DELETE: 'GUILD_ROLE_DELETE',
      GUILD_ROLE_UPDATE: 'GUILD_ROLE_UPDATE',
      GUILD_BAN_ADD: 'GUILD_BAN_ADD',
      GUILD_BAN_REMOVE: 'GUILD_BAN_REMOVE',
      GUILD_EMOJIS_UPDATE: 'GUILD_EMOJIS_UPDATE',
      CHANNEL_CREATE: 'CHANNEL_CREATE',
      CHANNEL_DELETE: 'CHANNEL_DELETE',
      CHANNEL_UPDATE: 'CHANNEL_UPDATE',
      CHANNEL_PINS_UPDATE: 'CHANNEL_PINS_UPDATE',
      MESSAGE_CREATE: 'MESSAGE_CREATE',
      MESSAGE_DELETE: 'MESSAGE_DELETE',
      MESSAGE_UPDATE: 'MESSAGE_UPDATE',
      MESSAGE_DELETE_BULK: 'MESSAGE_DELETE_BULK',
      MESSAGE_REACTION_ADD: 'MESSAGE_REACTION_ADD',
      MESSAGE_REACTION_REMOVE: 'MESSAGE_REACTION_REMOVE',
      MESSAGE_REACTION_REMOVE_ALL: 'MESSAGE_REACTION_REMOVE_ALL',
      MESSAGE_REACTION_REMOVE_EMOJI: 'MESSAGE_REACTION_REMOVE_EMOJI',
      THREAD_CREATE: 'THREAD_CREATE',
      THREAD_UPDATE: 'THREAD_UPDATE',
      THREAD_DELETE: 'THREAD_DELETE',
      THREAD_LIST_SYNC: 'THREAD_LIST_SYNC',
      THREAD_MEMBER_UPDATE: 'THREAD_MEMBER_UPDATE',
      THREAD_MEMBERS_UPDATE: 'THREAD_MEMBERS_UPDATE',
      USER_UPDATE: 'USER_UPDATE',
      PRESENCE_UPDATE: 'PRESENCE_UPDATE',
      TYPING_START: 'TYPING_START',
      VOICE_STATE_UPDATE: 'VOICE_STATE_UPDATE',
      VOICE_SERVER_UPDATE: 'VOICE_SERVER_UPDATE',
      WEBHOOKS_UPDATE: 'WEBHOOKS_UPDATE',
      INTERACTION_CREATE: 'INTERACTION_CREATE',
      STAGE_INSTANCE_CREATE: 'STAGE_INSTANCE_CREATE',
      STAGE_INSTANCE_UPDATE: 'STAGE_INSTANCE_UPDATE',
      STAGE_INSTANCE_DELETE: 'STAGE_INSTANCE_DELETE',
      GUILD_STICKERS_UPDATE: 'GUILD_STICKERS_UPDATE'
    },
    InviteScopes: [
      'applications.builds.read',
      'applications.commands',
      'applications.entitlements',
      'applications.store.update',
      'bot',
      'connections',
      'email',
      'identify',
      'guilds',
      'guilds.join',
      'gdm.join',
      'webhook.incoming'
    ],
    IntegrationExpireBehaviors: { '0': 'REMOVE_ROLE', '1': 'KICK', REMOVE_ROLE: 0, KICK: 1 },
    MessageTypes: [
      'DEFAULT',
      'RECIPIENT_ADD',
      'RECIPIENT_REMOVE',
      'CALL',
      'CHANNEL_NAME_CHANGE',
      'CHANNEL_ICON_CHANGE',
      'CHANNEL_PINNED_MESSAGE',
      'GUILD_MEMBER_JOIN',
      'USER_PREMIUM_GUILD_SUBSCRIPTION',
      'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1',
      'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2',
      'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3',
      'CHANNEL_FOLLOW_ADD',
      null,
      'GUILD_DISCOVERY_DISQUALIFIED',
      'GUILD_DISCOVERY_REQUALIFIED',
      'GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING',
      'GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING',
      'THREAD_CREATED',
      'REPLY',
      'APPLICATION_COMMAND',
      'THREAD_STARTER_MESSAGE',
      'GUILD_INVITE_REMINDER',
      'CONTEXT_MENU_COMMAND'
    ],
    SystemMessageTypes: [
      'RECIPIENT_ADD',
      'RECIPIENT_REMOVE',
      'CALL',
      'CHANNEL_NAME_CHANGE',
      'CHANNEL_ICON_CHANGE',
      'CHANNEL_PINNED_MESSAGE',
      'GUILD_MEMBER_JOIN',
      'USER_PREMIUM_GUILD_SUBSCRIPTION',
      'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1',
      'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2',
      'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3',
      'CHANNEL_FOLLOW_ADD',
      'GUILD_DISCOVERY_DISQUALIFIED',
      'GUILD_DISCOVERY_REQUALIFIED',
      'GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING',
      'GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING',
      'THREAD_CREATED',
      'THREAD_STARTER_MESSAGE',
      'GUILD_INVITE_REMINDER'
    ],
    ActivityTypes: {
      '0': 'PLAYING',
      '1': 'STREAMING',
      '2': 'LISTENING',
      '3': 'WATCHING',
      '4': 'CUSTOM',
      '5': 'COMPETING',
      PLAYING: 0,
      STREAMING: 1,
      LISTENING: 2,
      WATCHING: 3,
      CUSTOM: 4,
      COMPETING: 5
    },
    ChannelTypes: {
      '0': 'GUILD_TEXT',
      '1': 'DM',
      '2': 'GUILD_VOICE',
      '3': 'GROUP_DM',
      '4': 'GUILD_CATEGORY',
      '5': 'GUILD_NEWS',
      '6': 'GUILD_STORE',
      '10': 'GUILD_NEWS_THREAD',
      '11': 'GUILD_PUBLIC_THREAD',
      '12': 'GUILD_PRIVATE_THREAD',
      '13': 'GUILD_STAGE_VOICE',
      GUILD_TEXT: 0,
      DM: 1,
      GUILD_VOICE: 2,
      GROUP_DM: 3,
      GUILD_CATEGORY: 4,
      GUILD_NEWS: 5,
      GUILD_STORE: 6,
      GUILD_NEWS_THREAD: 10,
      GUILD_PUBLIC_THREAD: 11,
      GUILD_PRIVATE_THREAD: 12,
      GUILD_STAGE_VOICE: 13
    },
    TextBasedChannelTypes: [
      'DM',
      'GUILD_TEXT',
      'GUILD_NEWS',
      'GUILD_NEWS_THREAD',
      'GUILD_PUBLIC_THREAD',
      'GUILD_PRIVATE_THREAD'
    ],
    ThreadChannelTypes: [
      'GUILD_NEWS_THREAD',
      'GUILD_PUBLIC_THREAD',
      'GUILD_PRIVATE_THREAD'
    ],
    VoiceBasedChannelTypes: [ 'GUILD_VOICE', 'GUILD_STAGE_VOICE' ],
    ClientApplicationAssetTypes: { SMALL: 1, BIG: 2 },
    Colors: {
      DEFAULT: 0,
      WHITE: 16777215,
      AQUA: 1752220,
      GREEN: 5763719,
      BLUE: 3447003,
      YELLOW: 16705372,
      PURPLE: 10181046,
      LUMINOUS_VIVID_PINK: 15277667,
      FUCHSIA: 15418782,
      GOLD: 15844367,
      ORANGE: 15105570,
      RED: 15548997,
      GREY: 9807270,
      NAVY: 3426654,
      DARK_AQUA: 1146986,
      DARK_GREEN: 2067276,
      DARK_BLUE: 2123412,
      DARK_PURPLE: 7419530,
      DARK_VIVID_PINK: 11342935,
      DARK_GOLD: 12745742,
      DARK_ORANGE: 11027200,
      DARK_RED: 10038562,
      DARK_GREY: 9936031,
      DARKER_GREY: 8359053,
      LIGHT_GREY: 12370112,
      DARK_NAVY: 2899536,
      BLURPLE: 5793266,
      GREYPLE: 10070709,
      DARK_BUT_NOT_BLACK: 2895667,
      NOT_QUITE_BLACK: 2303786
    },
    ExplicitContentFilterLevels: {
      '0': 'DISABLED',
      '1': 'MEMBERS_WITHOUT_ROLES',
      '2': 'ALL_MEMBERS',
      DISABLED: 0,
      MEMBERS_WITHOUT_ROLES: 1,
      ALL_MEMBERS: 2
    },
    VerificationLevels: {
      '0': 'NONE',
      '1': 'LOW',
      '2': 'MEDIUM',
      '3': 'HIGH',
      '4': 'VERY_HIGH',
      NONE: 0,
      LOW: 1,
      MEDIUM: 2,
      HIGH: 3,
      VERY_HIGH: 4
    },
    APIErrors: {
      UNKNOWN_ACCOUNT: 10001,
      UNKNOWN_APPLICATION: 10002,
      UNKNOWN_CHANNEL: 10003,
      UNKNOWN_GUILD: 10004,
      UNKNOWN_INTEGRATION: 10005,
      UNKNOWN_INVITE: 10006,
      UNKNOWN_MEMBER: 10007,
      UNKNOWN_MESSAGE: 10008,
      UNKNOWN_OVERWRITE: 10009,
      UNKNOWN_PROVIDER: 10010,
      UNKNOWN_ROLE: 10011,
      UNKNOWN_TOKEN: 10012,
      UNKNOWN_USER: 10013,
      UNKNOWN_EMOJI: 10014,
      UNKNOWN_WEBHOOK: 10015,
      UNKNOWN_WEBHOOK_SERVICE: 10016,
      UNKNOWN_SESSION: 10020,
      UNKNOWN_BAN: 10026,
      UNKNOWN_SKU: 10027,
      UNKNOWN_STORE_LISTING: 10028,
      UNKNOWN_ENTITLEMENT: 10029,
      UNKNOWN_BUILD: 10030,
      UNKNOWN_LOBBY: 10031,
      UNKNOWN_BRANCH: 10032,
      UNKNOWN_STORE_DIRECTORY_LAYOUT: 10033,
      UNKNOWN_REDISTRIBUTABLE: 10036,
      UNKNOWN_GIFT_CODE: 10038,
      UNKNOWN_STREAM: 10049,
      UNKNOWN_PREMIUM_SERVER_SUBSCRIBE_COOLDOWN: 10050,
      UNKNOWN_GUILD_TEMPLATE: 10057,
      UNKNOWN_DISCOVERABLE_SERVER_CATEGORY: 10059,
      UNKNOWN_STICKER: 10060,
      UNKNOWN_INTERACTION: 10062,
      UNKNOWN_APPLICATION_COMMAND: 10063,
      UNKNOWN_APPLICATION_COMMAND_PERMISSIONS: 10066,
      UNKNOWN_STAGE_INSTANCE: 10067,
      UNKNOWN_GUILD_MEMBER_VERIFICATION_FORM: 10068,
      UNKNOWN_GUILD_WELCOME_SCREEN: 10069,
      UNKNOWN_GUILD_SCHEDULED_EVENT: 10070,
      UNKNOWN_GUILD_SCHEDULED_EVENT_USER: 10071,
      BOT_PROHIBITED_ENDPOINT: 20001,
      BOT_ONLY_ENDPOINT: 20002,
      CANNOT_SEND_EXPLICIT_CONTENT: 20009,
      NOT_AUTHORIZED: 20012,
      SLOWMODE_RATE_LIMIT: 20016,
      ACCOUNT_OWNER_ONLY: 20018,
      ANNOUNCEMENT_EDIT_LIMIT_EXCEEDED: 20022,
      CHANNEL_HIT_WRITE_RATELIMIT: 20028,
      CONTENT_NOT_ALLOWED: 20031,
      GUILD_PREMIUM_LEVEL_TOO_LOW: 20035,
      MAXIMUM_GUILDS: 30001,
      MAXIMUM_FRIENDS: 30002,
      MAXIMUM_PINS: 30003,
      MAXIMUM_RECIPIENTS: 30004,
      MAXIMUM_ROLES: 30005,
      MAXIMUM_WEBHOOKS: 30007,
      MAXIMUM_EMOJIS: 30008,
      MAXIMUM_REACTIONS: 30010,
      MAXIMUM_CHANNELS: 30013,
      MAXIMUM_ATTACHMENTS: 30015,
      MAXIMUM_INVITES: 30016,
      MAXIMUM_ANIMATED_EMOJIS: 30018,
      MAXIMUM_SERVER_MEMBERS: 30019,
      MAXIMUM_NUMBER_OF_SERVER_CATEGORIES: 30030,
      GUILD_ALREADY_HAS_TEMPLATE: 30031,
      MAXIMUM_THREAD_PARTICIPANTS: 30033,
      MAXIMUM_NON_GUILD_MEMBERS_BANS: 30035,
      MAXIMUM_BAN_FETCHES: 30037,
      MAXIMUM_NUMBER_OF_STICKERS_REACHED: 30039,
      MAXIMUM_PRUNE_REQUESTS: 30040,
      MAXIMUM_GUILD_WIDGET_SETTINGS_UPDATE: 30042,
      UNAUTHORIZED: 40001,
      ACCOUNT_VERIFICATION_REQUIRED: 40002,
      DIRECT_MESSAGES_TOO_FAST: 40003,
      REQUEST_ENTITY_TOO_LARGE: 40005,
      FEATURE_TEMPORARILY_DISABLED: 40006,
      USER_BANNED: 40007,
      TARGET_USER_NOT_CONNECTED_TO_VOICE: 40032,
      ALREADY_CROSSPOSTED: 40033,
      MISSING_ACCESS: 50001,
      INVALID_ACCOUNT_TYPE: 50002,
      CANNOT_EXECUTE_ON_DM: 50003,
      EMBED_DISABLED: 50004,
      CANNOT_EDIT_MESSAGE_BY_OTHER: 50005,
      CANNOT_SEND_EMPTY_MESSAGE: 50006,
      CANNOT_MESSAGE_USER: 50007,
      CANNOT_SEND_MESSAGES_IN_VOICE_CHANNEL: 50008,
      CHANNEL_VERIFICATION_LEVEL_TOO_HIGH: 50009,
      OAUTH2_APPLICATION_BOT_ABSENT: 50010,
      MAXIMUM_OAUTH2_APPLICATIONS: 50011,
      INVALID_OAUTH_STATE: 50012,
      MISSING_PERMISSIONS: 50013,
      INVALID_AUTHENTICATION_TOKEN: 50014,
      NOTE_TOO_LONG: 50015,
      INVALID_BULK_DELETE_QUANTITY: 50016,
      CANNOT_PIN_MESSAGE_IN_OTHER_CHANNEL: 50019,
      INVALID_OR_TAKEN_INVITE_CODE: 50020,
      CANNOT_EXECUTE_ON_SYSTEM_MESSAGE: 50021,
      CANNOT_EXECUTE_ON_CHANNEL_TYPE: 50024,
      INVALID_OAUTH_TOKEN: 50025,
      MISSING_OAUTH_SCOPE: 50026,
      INVALID_WEBHOOK_TOKEN: 50027,
      INVALID_ROLE: 50028,
      INVALID_RECIPIENTS: 50033,
      BULK_DELETE_MESSAGE_TOO_OLD: 50034,
      INVALID_FORM_BODY: 50035,
      INVITE_ACCEPTED_TO_GUILD_NOT_CONTAINING_BOT: 50036,
      INVALID_API_VERSION: 50041,
      FILE_UPLOADED_EXCEEDS_MAXIMUM_SIZE: 50045,
      INVALID_FILE_UPLOADED: 50046,
      CANNOT_SELF_REDEEM_GIFT: 50054,
      PAYMENT_SOURCE_REQUIRED: 50070,
      CANNOT_DELETE_COMMUNITY_REQUIRED_CHANNEL: 50074,
      INVALID_STICKER_SENT: 50081,
      INVALID_OPERATION_ON_ARCHIVED_THREAD: 50083,
      INVALID_THREAD_NOTIFICATION_SETTINGS: 50084,
      PARAMETER_EARLIER_THAN_CREATION: 50085,
      GUILD_NOT_AVAILABLE_IN_LOCATION: 50095,
      GUILD_MONETIZATION_REQUIRED: 50097,
      INSUFFICIENT_BOOSTS: 50101,
      TWO_FACTOR_REQUIRED: 60003,
      NO_USERS_WITH_DISCORDTAG_EXIST: 80004,
      REACTION_BLOCKED: 90001,
      RESOURCE_OVERLOADED: 130000,
      STAGE_ALREADY_OPEN: 150006,
      CANNOT_REPLY_WITHOUT_READ_MESSAGE_HISTORY_PERMISSION: 160002,
      MESSAGE_ALREADY_HAS_THREAD: 160004,
      THREAD_LOCKED: 160005,
      MAXIMUM_ACTIVE_THREADS: 160006,
      MAXIMUM_ACTIVE_ANNOUNCEMENT_THREADS: 160007,
      INVALID_JSON_FOR_UPLOADED_LOTTIE_FILE: 170001,
      UPLOADED_LOTTIES_CANNOT_CONTAIN_RASTERIZED_IMAGES: 170002,
      STICKER_MAXIMUM_FRAMERATE_EXCEEDED: 170003,
      STICKER_FRAME_COUNT_EXCEEDS_MAXIMUM_OF_1000_FRAMES: 170004,
      LOTTIE_ANIMATION_MAXIMUM_DIMENSIONS_EXCEEDED: 170005,
      STICKER_FRAME_RATE_IS_TOO_SMALL_OR_TOO_LARGE: 170006,
      STICKER_ANIMATION_DURATION_EXCEEDS_MAXIMUM_OF_5_SECONDS: 170007
    },
    DefaultMessageNotificationLevels: {
      '0': 'ALL_MESSAGES',
      '1': 'ONLY_MENTIONS',
      ALL_MESSAGES: 0,
      ONLY_MENTIONS: 1
    },
    MembershipStates: { '1': 'INVITED', '2': 'ACCEPTED', INVITED: 1, ACCEPTED: 2 },
    WebhookTypes: {
      '1': 'Incoming',
      '2': 'Channel Follower',
      '3': 'Application',
      Incoming: 1,
      'Channel Follower': 2,
      Application: 3
    },
    StickerTypes: { '1': 'STANDARD', '2': 'GUILD', STANDARD: 1, GUILD: 2 },
    StickerFormatTypes: {
      '1': 'PNG',
      '2': 'APNG',
      '3': 'LOTTIE',
      PNG: 1,
      APNG: 2,
      LOTTIE: 3
    },
    OverwriteTypes: { '0': 'role', '1': 'member', role: 0, member: 1 },
    ApplicationCommandTypes: {
      '1': 'CHAT_INPUT',
      '2': 'USER',
      '3': 'MESSAGE',
      CHAT_INPUT: 1,
      USER: 2,
      MESSAGE: 3
    },
    ApplicationCommandOptionTypes: {
      '1': 'SUB_COMMAND',
      '2': 'SUB_COMMAND_GROUP',
      '3': 'STRING',
      '4': 'INTEGER',
      '5': 'BOOLEAN',
      '6': 'USER',
      '7': 'CHANNEL',
      '8': 'ROLE',
      '9': 'MENTIONABLE',
      '10': 'NUMBER',
      SUB_COMMAND: 1,
      SUB_COMMAND_GROUP: 2,
      STRING: 3,
      INTEGER: 4,
      BOOLEAN: 5,
      USER: 6,
      CHANNEL: 7,
      ROLE: 8,
      MENTIONABLE: 9,
      NUMBER: 10
    },
    ApplicationCommandPermissionTypes: { '1': 'ROLE', '2': 'USER', ROLE: 1, USER: 2 },
    InteractionTypes: {
      '1': 'PING',
      '2': 'APPLICATION_COMMAND',
      '3': 'MESSAGE_COMPONENT',
      '4': 'APPLICATION_COMMAND_AUTOCOMPLETE',
      PING: 1,
      APPLICATION_COMMAND: 2,
      MESSAGE_COMPONENT: 3,
      APPLICATION_COMMAND_AUTOCOMPLETE: 4
    },
    InteractionResponseTypes: {
      '1': 'PONG',
      '4': 'CHANNEL_MESSAGE_WITH_SOURCE',
      '5': 'DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE',
      '6': 'DEFERRED_MESSAGE_UPDATE',
      '7': 'UPDATE_MESSAGE',
      '8': 'APPLICATION_COMMAND_AUTOCOMPLETE_RESULT',
      PONG: 1,
      CHANNEL_MESSAGE_WITH_SOURCE: 4,
      DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE: 5,
      DEFERRED_MESSAGE_UPDATE: 6,
      UPDATE_MESSAGE: 7,
      APPLICATION_COMMAND_AUTOCOMPLETE_RESULT: 8
    },
    MessageComponentTypes: {
      '1': 'ACTION_ROW',
      '2': 'BUTTON',
      '3': 'SELECT_MENU',
      ACTION_ROW: 1,
      BUTTON: 2,
      SELECT_MENU: 3
    },
    MessageButtonStyles: {
      '1': 'PRIMARY',
      '2': 'SECONDARY',
      '3': 'SUCCESS',
      '4': 'DANGER',
      '5': 'LINK',
      PRIMARY: 1,
      SECONDARY: 2,
      SUCCESS: 3,
      DANGER: 4,
      LINK: 5
    },
    MFALevels: { '0': 'NONE', '1': 'ELEVATED', NONE: 0, ELEVATED: 1 },
    NSFWLevels: {
      '0': 'DEFAULT',
      '1': 'EXPLICIT',
      '2': 'SAFE',
      '3': 'AGE_RESTRICTED',
      DEFAULT: 0,
      EXPLICIT: 1,
      SAFE: 2,
      AGE_RESTRICTED: 3
    },
    PrivacyLevels: { '1': 'PUBLIC', '2': 'GUILD_ONLY', PUBLIC: 1, GUILD_ONLY: 2 },
    PremiumTiers: {
      '0': 'NONE',
      '1': 'TIER_1',
      '2': 'TIER_2',
      '3': 'TIER_3',
      NONE: 0,
      TIER_1: 1,
      TIER_2: 2,
      TIER_3: 3
    },
    _cleanupSymbol: Symbol(djsCleanup)
  },
  DataResolver: [class DataResolver],
  DiscordAPIError: [class DiscordAPIError extends Error],
  Formatters: [class Formatters] {
    blockQuote: [Function: je],
    bold: [Function: Je],
    channelMention: [Function: Ye],
    codeBlock: [Function: Ue],
    formatEmoji: [Function: et],
    hideLinkEmbed: [Function: ze],
    hyperlink: [Function: Ke],
    inlineCode: [Function: Ge],
    italic: [Function: Fe],
    memberNicknameMention: [Function: Xe],
    quote: [Function: We],
    roleMention: [Function: Ze],
    spoiler: [Function: Qe],
    strikethrough: [Function: Ve],
    time: [Function: tt],
    TimestampStyles: {
      ShortTime: 't',
      LongTime: 'T',
      ShortDate: 'd',
      LongDate: 'D',
      ShortDateTime: 'f',
      LongDateTime: 'F',
      RelativeTime: 'R'
    },
    underscore: [Function: qe],
    userMention: [Function: He]
  },
  HTTPError: [class HTTPError extends Error],
  Intents: [class Intents extends BitField] {
    FLAGS: {
      GUILDS: 1,
      GUILD_MEMBERS: 2,
      GUILD_BANS: 4,
      GUILD_EMOJIS_AND_STICKERS: 8,
      GUILD_INTEGRATIONS: 16,
      GUILD_WEBHOOKS: 32,
      GUILD_INVITES: 64,
      GUILD_VOICE_STATES: 128,
      GUILD_PRESENCES: 256,
      GUILD_MESSAGES: 512,
      GUILD_MESSAGE_REACTIONS: 1024,
      GUILD_MESSAGE_TYPING: 2048,
      DIRECT_MESSAGES: 4096,
      DIRECT_MESSAGE_REACTIONS: 8192,
      DIRECT_MESSAGE_TYPING: 16384
    }
  },
  LimitedCollection: [class LimitedCollection extends Collection],
  MessageFlags: [class MessageFlags extends BitField] {
    FLAGS: {
      CROSSPOSTED: 1,
      IS_CROSSPOST: 2,
      SUPPRESS_EMBEDS: 4,
      SOURCE_MESSAGE_DELETED: 8,
      URGENT: 16,
      HAS_THREAD: 32,
      EPHEMERAL: 64,
      LOADING: 128
    }
  },
  Options: [class Options],
  Permissions: [class Permissions extends BitField] {
    FLAGS: {
      CREATE_INSTANT_INVITE: 1n,
      KICK_MEMBERS: 2n,
      BAN_MEMBERS: 4n,
      ADMINISTRATOR: 8n,
      MANAGE_CHANNELS: 16n,
      MANAGE_GUILD: 32n,
      ADD_REACTIONS: 64n,
      VIEW_AUDIT_LOG: 128n,
      PRIORITY_SPEAKER: 256n,
      STREAM: 512n,
      VIEW_CHANNEL: 1024n,
      SEND_MESSAGES: 2048n,
      SEND_TTS_MESSAGES: 4096n,
      MANAGE_MESSAGES: 8192n,
      EMBED_LINKS: 16384n,
      ATTACH_FILES: 32768n,
      READ_MESSAGE_HISTORY: 65536n,
      MENTION_EVERYONE: 131072n,
      USE_EXTERNAL_EMOJIS: 262144n,
      VIEW_GUILD_INSIGHTS: 524288n,
      CONNECT: 1048576n,
      SPEAK: 2097152n,
      MUTE_MEMBERS: 4194304n,
      DEAFEN_MEMBERS: 8388608n,
      MOVE_MEMBERS: 16777216n,
      USE_VAD: 33554432n,
      CHANGE_NICKNAME: 67108864n,
      MANAGE_NICKNAMES: 134217728n,
      MANAGE_ROLES: 268435456n,
      MANAGE_WEBHOOKS: 536870912n,
      MANAGE_EMOJIS_AND_STICKERS: 1073741824n,
      USE_APPLICATION_COMMANDS: 2147483648n,
      REQUEST_TO_SPEAK: 4294967296n,
      MANAGE_THREADS: 17179869184n,
      USE_PUBLIC_THREADS: 34359738368n,
      CREATE_PUBLIC_THREADS: 34359738368n,
      USE_PRIVATE_THREADS: 68719476736n,
      CREATE_PRIVATE_THREADS: 68719476736n,
      USE_EXTERNAL_STICKERS: 137438953472n,
      SEND_MESSAGES_IN_THREADS: 274877906944n,
      START_EMBEDDED_ACTIVITIES: 549755813888n
    },
    ALL: 1090921693183n,
    DEFAULT: 104324673n,
    STAGE_MODERATOR: 20971536n,
    defaultBit: 0n
  },
  RateLimitError: [class RateLimitError extends Error],
  SnowflakeUtil: [class SnowflakeUtil],
  SystemChannelFlags: [class SystemChannelFlags extends BitField] {
    FLAGS: {
      SUPPRESS_JOIN_NOTIFICATIONS: 1,
      SUPPRESS_PREMIUM_SUBSCRIPTIONS: 2,
      SUPPRESS_GUILD_REMINDER_NOTIFICATIONS: 4
    }
  },
  ThreadMemberFlags: [class ThreadMemberFlags extends BitField] { FLAGS: {} },
  UserFlags: [class UserFlags extends BitField] {
    FLAGS: {
      DISCORD_EMPLOYEE: 1,
      PARTNERED_SERVER_OWNER: 2,
      HYPESQUAD_EVENTS: 4,
      BUGHUNTER_LEVEL_1: 8,
      HOUSE_BRAVERY: 64,
      HOUSE_BRILLIANCE: 128,
      HOUSE_BALANCE: 256,
      EARLY_SUPPORTER: 512,
      TEAM_USER: 1024,
      BUGHUNTER_LEVEL_2: 16384,
      VERIFIED_BOT: 65536,
      EARLY_VERIFIED_BOT_DEVELOPER: 131072,
      DISCORD_CERTIFIED_MODERATOR: 262144
    }
  },
  Util: [class Util],
  version: '13.3.1',
  ApplicationCommandManager: [class ApplicationCommandManager extends CachedManager],
  ApplicationCommandPermissionsManager: [class ApplicationCommandPermissionsManager extends BaseManager],
  BaseGuildEmojiManager: [class BaseGuildEmojiManager extends CachedManager],
  CachedManager: [class CachedManager extends DataManager],
  ChannelManager: [class ChannelManager extends CachedManager],
  ClientVoiceManager: [class ClientVoiceManager],
  DataManager: [class DataManager extends BaseManager],
  GuildApplicationCommandManager: [class GuildApplicationCommandManager extends ApplicationCommandManager],
  GuildBanManager: [class GuildBanManager extends CachedManager],
  GuildChannelManager: [class GuildChannelManager extends CachedManager],
  GuildEmojiManager: [class GuildEmojiManager extends BaseGuildEmojiManager],
  GuildEmojiRoleManager: [class GuildEmojiRoleManager extends DataManager],
  GuildInviteManager: [class GuildInviteManager extends CachedManager],
  GuildManager: [class GuildManager extends CachedManager],
  GuildMemberManager: [class GuildMemberManager extends CachedManager],
  GuildMemberRoleManager: [class GuildMemberRoleManager extends DataManager],
  GuildStickerManager: [class GuildStickerManager extends CachedManager],
  MessageManager: [class MessageManager extends CachedManager],
  PermissionOverwriteManager: [class PermissionOverwriteManager extends CachedManager],
  PresenceManager: [class PresenceManager extends CachedManager],
  ReactionManager: [class ReactionManager extends CachedManager],
  ReactionUserManager: [class ReactionUserManager extends CachedManager],
  RoleManager: [class RoleManager extends CachedManager],
  StageInstanceManager: [class StageInstanceManager extends CachedManager],
  ThreadManager: [class ThreadManager extends CachedManager],
  ThreadMemberManager: [class ThreadMemberManager extends CachedManager],
  UserManager: [class UserManager extends CachedManager],
  VoiceStateManager: [class VoiceStateManager extends CachedManager],
  WebSocketManager: [class WebSocketManager extends EventEmitter],
  WebSocketShard: [class WebSocketShard extends EventEmitter],
  Activity: [class Activity],
  AnonymousGuild: [class AnonymousGuild extends BaseGuild],
  Application: [class Application extends Base],
  ApplicationCommand: [class ApplicationCommand extends Base],
  AutocompleteInteraction: [class AutocompleteInteraction extends Interaction],
  Base: [class Base],
  BaseCommandInteraction: [class BaseCommandInteraction extends Interaction],
  BaseGuild: [class BaseGuild extends Base],
  BaseGuildEmoji: [class BaseGuildEmoji extends Emoji],
  BaseGuildTextChannel: [class BaseGuildTextChannel extends GuildChannel],
  BaseGuildVoiceChannel: [class BaseGuildVoiceChannel extends GuildChannel],
  BaseMessageComponent: [class BaseMessageComponent],
  ButtonInteraction: [class ButtonInteraction extends MessageComponentInteraction],
  CategoryChannel: [class CategoryChannel extends GuildChannel],
  Channel: [class Channel extends Base],
  ClientApplication: [class ClientApplication extends Application],
  ClientPresence: [class ClientPresence extends Presence],
  ClientUser: [class ClientUser extends User],
  Collector: [class Collector extends EventEmitter],
  CommandInteraction: [class CommandInteraction extends BaseCommandInteraction],
  CommandInteractionOptionResolver: [class CommandInteractionOptionResolver],
  ContextMenuInteraction: [class ContextMenuInteraction extends BaseCommandInteraction],
  DMChannel: [class DMChannel extends Channel],
  Emoji: [class Emoji extends Base],
  Guild: [class Guild extends AnonymousGuild],
  GuildAuditLogs: [class GuildAuditLogs] {
    Actions: {
      ALL: null,
      GUILD_UPDATE: 1,
      CHANNEL_CREATE: 10,
      CHANNEL_UPDATE: 11,
      CHANNEL_DELETE: 12,
      CHANNEL_OVERWRITE_CREATE: 13,
      CHANNEL_OVERWRITE_UPDATE: 14,
      CHANNEL_OVERWRITE_DELETE: 15,
      MEMBER_KICK: 20,
      MEMBER_PRUNE: 21,
      MEMBER_BAN_ADD: 22,
      MEMBER_BAN_REMOVE: 23,
      MEMBER_UPDATE: 24,
      MEMBER_ROLE_UPDATE: 25,
      MEMBER_MOVE: 26,
      MEMBER_DISCONNECT: 27,
      BOT_ADD: 28,
      ROLE_CREATE: 30,
      ROLE_UPDATE: 31,
      ROLE_DELETE: 32,
      INVITE_CREATE: 40,
      INVITE_UPDATE: 41,
      INVITE_DELETE: 42,
      WEBHOOK_CREATE: 50,
      WEBHOOK_UPDATE: 51,
      WEBHOOK_DELETE: 52,
      EMOJI_CREATE: 60,
      EMOJI_UPDATE: 61,
      EMOJI_DELETE: 62,
      MESSAGE_DELETE: 72,
      MESSAGE_BULK_DELETE: 73,
      MESSAGE_PIN: 74,
      MESSAGE_UNPIN: 75,
      INTEGRATION_CREATE: 80,
      INTEGRATION_UPDATE: 81,
      INTEGRATION_DELETE: 82,
      STAGE_INSTANCE_CREATE: 83,
      STAGE_INSTANCE_UPDATE: 84,
      STAGE_INSTANCE_DELETE: 85,
      STICKER_CREATE: 90,
      STICKER_UPDATE: 91,
      STICKER_DELETE: 92,
      THREAD_CREATE: 110,
      THREAD_UPDATE: 111,
      THREAD_DELETE: 112
    },
    Targets: {
      ALL: 'ALL',
      GUILD: 'GUILD',
      CHANNEL: 'CHANNEL',
      USER: 'USER',
      ROLE: 'ROLE',
      INVITE: 'INVITE',
      WEBHOOK: 'WEBHOOK',
      EMOJI: 'EMOJI',
      MESSAGE: 'MESSAGE',
      INTEGRATION: 'INTEGRATION',
      STAGE_INSTANCE: 'STAGE_INSTANCE',
      STICKER: 'STICKER',
      THREAD: 'THREAD',
      UNKNOWN: 'UNKNOWN'
    },
    Entry: [class GuildAuditLogsEntry]
  },
  GuildAuditLogsEntry: [class GuildAuditLogsEntry],
  GuildBan: [class GuildBan extends Base],
  GuildChannel: [class GuildChannel extends Channel],
  GuildEmoji: [class GuildEmoji extends BaseGuildEmoji],
  GuildMember: [class GuildMember extends Base],
  GuildPreview: [class GuildPreview extends Base],
  GuildPreviewEmoji: [class GuildPreviewEmoji extends BaseGuildEmoji],
  GuildTemplate: [class GuildTemplate extends Base] {
    GUILD_TEMPLATES_PATTERN: /discord(?:app)?\.(?:com\/template|new)\/([\w-]{2,255})/gi
  },
  Integration: [class Integration extends Base],
  IntegrationApplication: [class IntegrationApplication extends Application],
  Interaction: [class Interaction extends Base],
  InteractionCollector: [class InteractionCollector extends Collector],
  InteractionWebhook: [class InteractionWebhook],
  Invite: [class Invite extends Base] {
    INVITES_PATTERN: /discord(?:(?:app)?\.com\/invite|\.gg(?:\/invite)?)\/([\w-]{2,255})/gi
  },
  InviteStageInstance: [class InviteStageInstance extends Base],
  InviteGuild: [class InviteGuild extends AnonymousGuild],
  Message: [class Message extends Base],
  MessageActionRow: [class MessageActionRow extends BaseMessageComponent],
  MessageAttachment: [class MessageAttachment],
  MessageButton: [class MessageButton extends BaseMessageComponent],
  MessageCollector: [class MessageCollector extends Collector],
  MessageComponentInteraction: [class MessageComponentInteraction extends Interaction],
  MessageEmbed: [class MessageEmbed],
  MessageMentions: [class MessageMentions] {
    EVERYONE_PATTERN: /@(everyone|here)/g,
    USERS_PATTERN: /<@!?(\d{17,19})>/g,
    ROLES_PATTERN: /<@&(\d{17,19})>/g,
    CHANNELS_PATTERN: /<#(\d{17,19})>/g
  },
  MessagePayload: [class MessagePayload],
  MessageReaction: [class MessageReaction],
  MessageSelectMenu: [class MessageSelectMenu extends BaseMessageComponent],
  NewsChannel: [class NewsChannel extends BaseGuildTextChannel],
  OAuth2Guild: [class OAuth2Guild extends BaseGuild],
  PartialGroupDMChannel: [class PartialGroupDMChannel extends Channel],
  PermissionOverwrites: [class PermissionOverwrites extends Base],
  Presence: [class Presence extends Base],
  ReactionCollector: [class ReactionCollector extends Collector],
  ReactionEmoji: [class ReactionEmoji extends Emoji],
  RichPresenceAssets: [class RichPresenceAssets],
  Role: [class Role extends Base],
  SelectMenuInteraction: [class SelectMenuInteraction extends MessageComponentInteraction],
  StageChannel: [class StageChannel extends BaseGuildVoiceChannel],
  StageInstance: [class StageInstance extends Base],
  Sticker: [class Sticker extends Base],
  StickerPack: [class StickerPack extends Base],
  StoreChannel: [class StoreChannel extends GuildChannel],
  Team: [class Team extends Base],
  TeamMember: [class TeamMember extends Base],
  TextChannel: [class TextChannel extends BaseGuildTextChannel],
  ThreadChannel: [class ThreadChannel extends Channel],
  ThreadMember: [class ThreadMember extends Base],
  Typing: [class Typing extends Base],
  User: [class User extends Base],
  VoiceChannel: [class VoiceChannel extends BaseGuildVoiceChannel],
  VoiceRegion: [class VoiceRegion],
  VoiceState: [class VoiceState extends Base],
  Webhook: [class Webhook],
  Widget: [class Widget extends Base],
  WidgetMember: [class WidgetMember extends Base],
  WelcomeChannel: [class WelcomeChannel extends Base],
  WelcomeScreen: [class WelcomeScreen extends Base],
  WebSocket: {
    WebSocket: <ref *2> [class WebSocket extends EventEmitter] {
      CONNECTING: 0,
      OPEN: 1,
      CLOSING: 2,
      CLOSED: 3,
      createWebSocketStream: [Function: createWebSocketStream],
      Server: [class WebSocketServer extends EventEmitter],
      Receiver: [class Receiver extends Writable],
      Sender: [class Sender],
      WebSocket: [Circular *2],
      WebSocketServer: [class WebSocketServer extends EventEmitter]
    },
    encoding: 'json',
    pack: [Function: stringify],
    unpack: [Function (anonymous)],
    create: [Function (anonymous)],
    CONNECTING: 0,
    OPEN: 1,
    CLOSING: 2,
    CLOSED: 3
  }
}
